"""Initial schema

Revision ID: 83697f896617
Revises:
Create Date: 2025-05-31 09:22:34.912059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83697f896617'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.create_index(op.f('ix_games_name'), 'games', ['name'], unique=False)

    op.create_table('users',
    sa.Column('steam_id', sa.String(), nullable=False),
    sa.Column('persona_name', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('steam_id')
    )
    op.create_index(op.f('ix_users_persona_name'), 'users', ['persona_name'], unique=False)
    op.create_index(op.f('ix_users_steam_id'), 'users', ['steam_id'], unique=False)

    op.create_table('user_game_playtime',
    sa.Column('user_steam_id', sa.String(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('playtime_forever', sa.Integer(), nullable=True, default=0),
    sa.Column('playtime_2weeks', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_steam_id'], ['users.steam_id'], ),
    sa.PrimaryKeyConstraint('user_steam_id', 'game_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_game_playtime')
    op.drop_index(op.f('ix_users_steam_id'), table_name='users')
    op.drop_index(op.f('ix_users_persona_name'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_games_name'), table_name='games')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
