"""Add genres and tags to games table

Revision ID: f562d94addfc
Revises: 83697f896617
Create Date: 2025-05-31 09:31:08.294871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f562d94addfc'
down_revision: Union[str, None] = '83697f896617' # Ensure this points to the previous migration
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('genres', sa.String(), nullable=True))
    op.add_column('games', sa.Column('tags', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'tags')
    op.drop_column('games', 'genres')
    # ### end Alembic commands ###
